DCCar/urls.py
from DCCar import views
from django.conf.urls import url

__author__ = 'milenkotomic'

app_name = 'DCCar'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<car_id>[0-9]+)/$', views.car_detail, name='car_detail'),
    url(r'^(?P<car_id>[0-9]+)/reserve/$', views.reserve, name='reserve'),
]

IngSoft/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dccar/', include('DCCar.urls'))
]

DCCar/models.py
from __future__ import unicode_literals

from django.db import models


class Car(models.Model):
    brand = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    year = models.IntegerField(default=0)
    license_plate = models.CharField(max_length=10)
    
    def __str__(self):
        return self.license_plate
    
    
class Reservation(models.Model):
    start = models.DateField()
    end = models.DateField()
    car =  models.ForeignKey(Car, on_delete=models.CASCADE)
    

DCCar/forms.py
from django.forms import ModelForm, forms

from DCCar.models import Reservation

__author__ = 'milenkotomic'


class ReserveForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['start', 'end', 'car']

DCCar/views.py
from django.http import HttpResponse
# from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

from DCCar.forms import ReserveForm
from DCCar.models import Car


def index(request):
    cars = Car.objects.all()
    context = {
        'cars': cars
    }
    return render(request, 'DCCar/index.html', context)

def car_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    context ={
        'car': car
    }
    return render(request, 'DCCar/car_details.html', context)


def reserve(request, car_id):
    car = Car.objects.get(id=car_id)
    if request.POST:
        form = ReserveForm(request.POST)
        print "hola"
        if form.is_valid():
            print "hola"
            form.save()
        else:
            return render(request, 'DCCar/reserve.html', {'car': car, 'form': form})
            
    form = ReserveForm(initial={'car': car})
    context = {
        'car': car,
        'form': form
    }
    return render(request, 'DCCar/reserve.html', context)

templates/DCCar/car_details.html
<h1>Detalles del auto</h1>
<table>
    <tr>
        <th>Marca</th>
        <td>{{ car.brand }}</td>
    </tr>
    <tr>
        <th>Modelo</th>
        <td>{{ car.model }}</td>
    </tr>
    <tr>
        <th>Año</th>
        <td>{{ car.year }}</td>
    </tr>
    <tr>
        <th>Patente</th>
        <td>{{ car.license_plate }}</td>
    </tr>
</table>
<a href="{% url 'DCCar:reserve' car.id %}">Reservar</a>

templates/DCCar/index.html
<h1>Bienvenido a DCCar</h1>

{% for car in cars %}
    <h2>{{ car.brand }} - {{ car.model }}</h2>
    <ul>
        <li>{{ car.year }}</li>
        <li>{{ car.license_plate }}</li>
    </ul>
    <a href="{% url 'DCCar:car_detail' car.id %}">Más detalles</a>
{% endfor %}

templates/DCCar/reserve.html
<h1>Reservar auto patente {{ car.license_plate }}</h1>

<form action="" method="post">
{% csrf_token %}

{{ form.car.as_hidden }}
{{ form.start.errors }}
<label>{{ form.start.label}}:</label>{{ form.start }}
<br>
{{ form.end.errors }}
<label>{{ form.end.label}}:</label>{{ form.end }}
<br>

<input type="submit" value="Enviar" />
</form>